"""Shared data structures for the Copilot agent orchestration runtime."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any, Mapping, Sequence

if TYPE_CHECKING:  # pragma: no cover - import cycle hint for type checkers
    from .missions import Mission


class MissionStatus(Enum):
    """High-level outcome for an executed mission."""

    SUCCEEDED = "succeeded"
    FAILED = "failed"
    BLOCKED = "blocked"


class ThoughtType(Enum):
    """Classification for planner-generated thoughts."""

    ACTION = "action"
    FINISH = "finish"


@dataclass(frozen=True)
class ToolCall:
    """Represents a planner-requested tool invocation."""

    name: str
    arguments: Mapping[str, Any]


@dataclass(frozen=True)
class Thought:
    """LLM reasoning output generated by the planner."""

    content: str
    type: ThoughtType
    tool_call: ToolCall | None = None


@dataclass(frozen=True)
class ToolResult:
    """Canonical result structure returned by tools."""

    success: bool
    output: Any | None = None
    error: str | None = None


@dataclass(frozen=True)
class AgentStep:
    """Single reasoning + action cycle executed by the agent."""

    thought: Thought
    result: ToolResult | None = None


@dataclass(frozen=True)
class MissionOutcome:
    """Outcome summary for an executed mission."""

    status: MissionStatus
    steps: Sequence[AgentStep]
    summary: str | None = None


@dataclass(frozen=True)
class ExecutionContext:
    """Runtime context provided to the agent when executing a mission."""

    inputs: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentState:
    """Immutable snapshot of mission progress consumed by planners."""

    mission: "Mission"
    context: ExecutionContext
    steps: Sequence[AgentStep] = field(default_factory=tuple)

    def with_step(self, step: AgentStep) -> "AgentState":
        """Return a new state that includes the provided step."""

        return AgentState(mission=self.mission, context=self.context, steps=(*self.steps, step))
